CarShop.Web/Controllers/CarsController.cs
namespace CarShop.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using Infrastructure.Extensions;
    using CarShop.Services;

    public class CarsController : Controller
    {
        private readonly ICarService carService;

        public CarsController(ICarService carService)
        {
            this.carService = carService;
        }

        public async Task<IActionResult> Details(int id)
        {
            if (!await this.carService.Exists(id))
            {
                this.TempData.AddErrorMessage(WebConstants.NotFound);
                return this.RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var carDetails = await this.carService.Details(id);

            return this.View(carDetails);
        }
    }
}

CarShop.Web/Controllers/HomeController.cs
namespace CarShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using CarShop.Web.Models;
    using CarShop.Services;
    using CarShop.Data.EntityModels;

    public class HomeController : Controller
    {
        private readonly ICarService carService;

        public HomeController(ICarService recordingService)
        {
            this.carService = recordingService;
        }

        public async Task<IActionResult> Index()
        {
            var recordingsData = await this.carService.GetCarsAsync();
            return View(recordingsData);
        }

        public async Task<IActionResult> ModelSearch(string search)
        {
            var carModel = await this.carService.CarModelSearch(search);
            if (carModel != null)
            {
                return View("Index", carModel);
            }
            else
            {
                return BadRequest("Sorry no results");
            }
        }

        public async Task<IActionResult> TypeSearch(int id)
        {
            var carType = await this.carService.CarTypeSearch(id);
            return View("Index", carType);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult More()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Cart()
        {
            return View();
        }
    }
}

CarShop.Web/Controllers/ShoppingCartController.cs
namespace CarShop.Web.Controllers
{
    using AutoMapper.QueryableExtensions;

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Data;
    using Services;
    using CarShop.Data.EntityModels;
    using CarShop.Web.Models;
    using Web.Infrastructure.Extensions;
    using CarShop.Web.Models.ShoppingCartViewModels;

    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartManager shoppingCartManager;
        private readonly CarShopDbContext db;
        private readonly UserManager<User> userManager;

        public ShoppingCartController(
            IShoppingCartManager shoppingCartManager,
            CarShopDbContext db,
            UserManager<User> userManager)
        {
            this.shoppingCartManager = shoppingCartManager;
            this.db = db;
            this.userManager = userManager;
        }

        public IActionResult AddToCart(int carId, int extraId)
        {
            var carFormat = this.db
                .CarInfo
                .Where(rf => rf.ExtraId == extraId
                        && rf.CarId == carId)
                .FirstOrDefault();

            if (carFormat == null)
            {
                this.TempData.AddErrorMessage(WebConstants.ExtraNotFound);
                return this.RedirectToAction(nameof(HomeController.Index), "Home");
            }

            if (carFormat.Quantity == 0)
            {
                this.TempData.AddErrorMessage(WebConstants.NoQuantity);
                return this.RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();
            this.shoppingCartManager.AddToCart(shoppingCartId, carId, extraId);

            return this.RedirectToAction(nameof(Items));
        }

        public IActionResult Items()
        {
            var itemsWithDetails = this.GetShoppingCartItems();

            return View(itemsWithDetails);
        }

        public IActionResult Remove(int recordingId, int formatId)
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();
            this.shoppingCartManager.RemoveFromCart(shoppingCartId, recordingId, formatId);

            return this.RedirectToAction(nameof(Items));
        }

        public IActionResult IncreaseQuantity(int recordingId, int formatId)
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();
            this.shoppingCartManager.IncreaseQuantity(shoppingCartId, recordingId, formatId);

            return this.RedirectToAction(nameof(Items));
        }

        public IActionResult DescreaseQuantity(int recordingId, int formatId)
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();
            this.shoppingCartManager.DecreaseQuantity(shoppingCartId, recordingId, formatId);

            return this.RedirectToAction(nameof(Items));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> FinishOrder(decimal orderTotal)
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();

            if (orderTotal <= 0)
            {
                this.TempData.AddErrorMessage(WebConstants.IsEmpty);

                this.shoppingCartManager.Clear(shoppingCartId);

                return this.RedirectToAction(nameof(Items));
            }

            var cartItems = this.GetShoppingCartItems();
            var order = new Order
            {
                UserId = this.userManager.GetUserId(this.User),
                OrderTotal = orderTotal
            };

            var orderItems = new List<OrderItem>();
            foreach (var item in cartItems)
            {
                orderItems.Add(new OrderItem
                {
                    CarId = item.CarId,
                    CarTitle = item.CarTitle,
                    ExtraId = item.ExtraId,
                    ExtraName = item.ExtraName,
                    Brand = this.db
                        .Cars
                        .Where(r => r.Id == item.CarId)
                        .Select(r => r.Brand.Name)
                        .FirstOrDefault(),
                    Quantity = item.Quantity,
                    Price = item.Price,
                    Discount = item.Discount
                });

                // update remaining Qty in db
                var carFormat = this.db
                    .CarInfo
                    .Where(rf => rf.ExtraId == item.ExtraId
                              && rf.CarId == item.CarId)
                    .FirstOrDefault();
                carFormat.Quantity -= item.Quantity;
                this.db.CarInfo.Update(carFormat);
            }

            order.OrderItems = orderItems;

            if (orderTotal != order.OrderItems
                            .Sum(i => i.Quantity * i.Price * (1 - (decimal)i.Discount / 100)))
            {
                this.TempData.AddErrorMessage(WebConstants.NotValid);
                return this.RedirectToAction(nameof(Items));
            }

            await this.db.Orders.AddAsync(order);
            await this.db.SaveChangesAsync();

            this.TempData.AddSuccessMessage(WebConstants.Completed);

            this.shoppingCartManager.Clear(shoppingCartId);

            return this.RedirectToAction(nameof(Items));
        }

        private List<CartItemViewModel> GetShoppingCartItems()
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();

            var items = this.shoppingCartManager.GetItems(shoppingCartId);

            var itemIds = items
                .Select(i => $"{i.CarId}:{i.ExtraId}")
                .ToList();

            var itemQuantitiesInStore = this.db
                .CarInfo
                .Where(rf => itemIds.Contains($"{rf.CarId}:{rf.ExtraId}"))
                .ToDictionary(i => $"{i.CarId}:{i.ExtraId}", i => i.Quantity);

            var itemQuantities = items.ToDictionary(i => $"{i.CarId}:{i.ExtraId}", i => i.Quantity);

            var itemsWithDetails = this.db
                .CarInfo
                .Where(rf => itemIds.Contains($"{rf.CarId}:{rf.ExtraId}"))  
                .ProjectTo<CartItemViewModel>()
                .ToList();

            itemsWithDetails
                .ForEach(i => i.Quantity = Math.Min(
                    itemQuantities[$"{i.CarId}:{i.ExtraId}"],
                    itemQuantitiesInStore[$"{i.CarId}:{i.ExtraId}"]));

            return itemsWithDetails;
        }
    }
}

CarShop.Web/Views/Home/Index.cshtml
@model IEnumerable<CartItemWithDetailsServiceModel>
@{
    ViewData["Title"] = "Home Page";
}

@foreach (var car in Model)
{
    <div class="col-sm-6 col-md-4 col-lg-3 p-b-35  isotope-item women">
        <!-- Block2 -->
        <div class="block2">
            <div class="block2-pic hov-img0">
                <a class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6"
                   asp-controller="Cars" asp-action=@nameof(CarsController.Details)
                   asp-route-id=@car.CarId>
                    <img src=@car.ImageUrl alt=@car.CarTitle width="287" height="175" asp-append-version="true" />
                </a>
            </div>
            <div class="block2-txt flex-w flex-t p-t-14">
                <div class="block2-txt-child1 flex-col-l ">
                    <a class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6"
                       asp-controller="Cars" asp-action=@nameof(CarsController.Details)
                       asp-route-id=@car.CarId>
                        <h3>@car.BrandName</h3>
                    </a>
                    <a class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6"
                       asp-controller="Cars" asp-action=@nameof(CarsController.Details)
                       asp-route-id=@car.CarId>
                        <span class="stext-101 m-t-4">
                            @car.CarTitle
                        </span>
                    </a>
                    <span class="stext-101 m-t-4">
                        @car.CarType        @car.ReleaseDate.ToString("yyyy")
                    </span>
                    <span class="stext-108">
                        Engine: @car.Engine -  @car.Fuel
                    </span>

                    <div class="stext-109">
                        @car.ExtraName
                    </div>
                    <div class="stext-109">
                        Net Price <b>@((car.Price * (1 - (decimal)car.Discount / 100)).ToCurrency())</b>
                    </div>
                    <div class="stext-109">
                        <a asp-area="" asp-controller="ShoppingCart" asp-action=@nameof(ShoppingCartController.AddToCart)
                           asp-route-carId=@car.CarId asp-route-extraId=@car.ExtraId
                           class="btn btn-default  btn-sm m-t-9">Add to Cart</a>
                    </div>
                </div>
                <div class="block2-txt-child2 flex-r p-t-3">
                    <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
                        <img class="icon-heart1 dis-block trans-04" src="~/images/icons/icon-heart-01.png" alt="ICON">
                        <img class="icon-heart2 dis-block trans-04 ab-t-l" src="~/images/icons/icon-heart-02.png" alt="ICON">
                    </a>
                </div>
            </div>
        </div>
    </div>
}